default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  url: <%= ENV.fetch("DATABASE_URL") %>

development:
  <<: *default
  database: smartgym_api_development
  host: db

test:
  <<: *default
  database: smartgym_api_test
  host: db

production:
  <<: *default
  database: smartgym_api_production
  username: smartgym_api
  password: <%= ENV["SMARTGYM_API_DATABASE_PASSWORD"] %>
  host: db
